version: '3'
volumes:
  db_data: {}
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
          - ./db_data:/var/lib/mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=sos
          - MYSQL_USER=viacheslav
          - MYSQL_PASSWORD=1234
        ports:
          - "8082:3306"
  node-sos:
        build: .
        ports:
          - "56733:8080"
        working_dir: /application
        volumes:
          - .:/application
        depends_on:
          - mysql